name: C++ GTest Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-2022
          - ubuntu-24.04
          - macos-14 # arm64
          - macos-13
        compiler:
          - llvm
          - gcc
          - gcc-9

    steps:
      # 检查代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 C++ 环境
      - name: Setup C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      # 安装必要的依赖（仅适用于 Linux）
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make libgtest-dev
      # 安装必要的依赖（仅适用于 macOS）
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake gtest

      # 配置和构建项目
      - name: Configure and Build
        run: |
          cmake -S. -Bbuild
          cmake --build build -j

      # 运行 gtest 测试
      - name: Run GTest Tests
        run: |
          ./build/test/test_main
